version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: market

volumes:
  postgres_data: {}

  #check has connection with postgress
  #    telnet localhost 5432

  # show logs
  #    docker run -it postgres bash

